spring:
  application:
    name: "cloud-server"

server:
  port: 6868

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka